In [1]:
import numpy as np
import pandas as pd
import pymssql
import pyodbc
from datetime import datetime, timedelta
import re
from dateutil.parser import parse
import glob
from tqdm import tqdm
import argparse
import sys
import openpyxl as opx
import xlrd
import time
import math
import seaborn as sns
import random
import matplotlib
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
from matplotlib import font_manager, rc
# matplotlib.rcParams['axes.unicode_minus'] = False
# font_path = "C:/Windows/Fonts/malgun.TTF"
# font = font_manager.FontProperties(fname=font_path).get_name()
# rc('font', family=font)
# %matplotlib inline
# plt.rc("font", family = "Malgun Gothic")
from copy import deepcopy
from pytimekr import pytimekr


from sklearn.model_selection import train_test_split, GridSearchCV
from torch.utils.data import DataLoader, Dataset
import torch.optim as optim
import torch.nn.functional as F
import torch.nn as nn
# import torchvision.transforms as transforms
# import torchvision
import torch


In [3]:
def generate_square_subsequent_mask(dim1, dim2): 
    return torch.triu(torch.ones(dim1, dim2) * float('-inf'), diagonal=1)

# Input length
enc_seq_len = 4

# Output length
output_sequence_length = 2

# Make src mask for decoder with size:
tgt_mask = generate_square_subsequent_mask(
    dim1=output_sequence_length,
    dim2=output_sequence_length
   )

src_mask = generate_square_subsequent_mask(
    dim1=output_sequence_length,
    dim2=enc_seq_len
    )

In [4]:
tgt_mask

tensor([[0., -inf],
        [0., 0.]])

In [5]:
src_mask

tensor([[0., -inf, -inf, -inf],
        [0., 0., -inf, -inf]])

In [8]:
torch.triu(torch.ones(4, 2), diagonal=1)

tensor([[0., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])