In [1]:
import os
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
# from utils.timefeatures import time_features
import warnings

# 데이터로더 내 일부 클래스 로드

In [2]:
class Dataset_ETT_minute(Dataset):
    def __init__(self, root_path, flag='train', size=None,
                 features='S', data_path='ETTm1.csv',
                 target='OT', scale=True, timeenc=0, freq='t'):
        # size [seq_len, label_len, pred_len]
        # info
        if size == None:
            self.seq_len = 24 * 4 * 4
            self.label_len = 24 * 4
            self.pred_len = 24 * 4
        else:
            self.seq_len = size[0]
            self.label_len = size[1]
            self.pred_len = size[2]
        # init
        assert flag in ['train', 'test', 'val']
        type_map = {'train': 0, 'val': 1, 'test': 2}
        self.set_type = type_map[flag]

        self.features = features
        self.target = target
        self.scale = scale
        self.timeenc = timeenc
        self.freq = freq

        self.root_path = root_path
        self.data_path = data_path
        self.__read_data__()

    def __read_data__(self):
        self.scaler = StandardScaler()
        df_raw = pd.read_csv(os.path.join(self.root_path,
                                          self.data_path))

        border1s = [0, 12 * 30 * 24 * 4 - self.seq_len, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4 - self.seq_len]
        border2s = [12 * 30 * 24 * 4, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4, 12 * 30 * 24 * 4 + 8 * 30 * 24 * 4]
        border1 = border1s[self.set_type]
        border2 = border2s[self.set_type]

        if self.features == 'M' or self.features == 'MS':
            cols_data = df_raw.columns[1:]
            df_data = df_raw[cols_data]
        elif self.features == 'S':
            df_data = df_raw[[self.target]]

        if self.scale:
            train_data = df_data[border1s[0]:border2s[0]]
            self.scaler.fit(train_data.values)
            data = self.scaler.transform(df_data.values)
        else:
            data = df_data.values

        df_stamp = df_raw[['date']][border1:border2]
        df_stamp['date'] = pd.to_datetime(df_stamp.date)
        if self.timeenc == 0:
            df_stamp['month'] = df_stamp.date.apply(lambda row: row.month, 1)
            df_stamp['day'] = df_stamp.date.apply(lambda row: row.day, 1)
            df_stamp['weekday'] = df_stamp.date.apply(lambda row: row.weekday(), 1)
            df_stamp['hour'] = df_stamp.date.apply(lambda row: row.hour, 1)
            df_stamp['minute'] = df_stamp.date.apply(lambda row: row.minute, 1)
            df_stamp['minute'] = df_stamp.minute.map(lambda x: x // 15)
            data_stamp = df_stamp.drop(['date'], 1).values
        elif self.timeenc == 1:
            data_stamp = time_features(pd.to_datetime(df_stamp['date'].values), freq=self.freq)
            data_stamp = data_stamp.transpose(1, 0)

        self.data_x = data[border1:border2]
        self.data_y = data[border1:border2]
        self.data_stamp = data_stamp

    def __getitem__(self, index):
        s_begin = index
        s_end = s_begin + self.seq_len
        r_begin = s_end - self.label_len
        r_end = r_begin + self.label_len + self.pred_len

        seq_x = self.data_x[s_begin:s_end]
        seq_y = self.data_y[r_begin:r_end]
        seq_x_mark = self.data_stamp[s_begin:s_end]
        seq_y_mark = self.data_stamp[r_begin:r_end]

        return seq_x, seq_y, seq_x_mark, seq_y_mark

    def __len__(self):
        return len(self.data_x) - self.seq_len - self.pred_len + 1

    def inverse_transform(self, data):
        return self.scaler.inverse_transform(data)

# 클래스 테스트

In [ ]:
# 데이터 경로 설정
root_path = './ETT-small'
data_path = 'ETTm1.csv'

In [ ]:
# 원본 데이터 확인
df = pd.read_csv(os.path.join(root_path, data_path))
print("원본 데이터 shape:", df.shape)
print("\n첫 5행 데이터:")
print(df.head())
print("\n컬럼명:", df.columns.tolist())

In [ ]:
# Dataset 인스턴스 생성 (train, val, test 각각)
train_dataset = Dataset_ETT_minute(
    root_path=root_path,
    data_path=data_path,
    flag='train',    
    size=[96, 48, 48],  # [seq_len, label_len, pred_len]
    features='M',  # 다변량 데이터 사용
    target='OT'  # 목표변수
)

val_dataset = Dataset_ETT_minute(
    root_path=root_path,
    data_path=data_path,
    flag='val',
    scale='False',
    size=[96, 48, 48],
    features='M',
    target='OT'
)

test_dataset = Dataset_ETT_minute(
    root_path=root_path,
    data_path=data_path,
    flag='test',
    scale='False',
    size=[96, 48, 48],
    features='M',
    target='OT'
)

# 데이터셋 크기 확인
print("\n데이터셋 크기:")
print(f"Train: {len(train_dataset)}")
print(f"Validation: {len(val_dataset)}")
print(f"Test: {len(test_dataset)}")

In [ ]:
# 첫 번째 배치 데이터 확인
first_batch = train_dataset[0]
seq_x, seq_y, seq_x_mark, seq_y_mark = first_batch

print("\n첫 번째 배치 데이터 shape:")
print(f"seq_x shape: {seq_x.shape}")  # 입력 시퀀스
print(f"seq_y shape: {seq_y.shape}")  # 타겟 시퀀스
print(f"seq_x_mark shape: {seq_x_mark.shape}")  # 입력 시퀀스의 시간 특성
print(f"seq_y_mark shape: {seq_y_mark.shape}")  # 타겟 시퀀스의 시간 특성

In [ ]:
seq_x

In [ ]:
seq_y

In [ ]:
seq_x_mark

In [ ]:
seq_y_mark

In [ ]:
# DataLoader를 사용한 배치 데이터 생성
train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)
# 첫 번째 배치 확인
for batch in train_loader:
    batch_x, batch_y, batch_x_mark, batch_y_mark = batch
    print("\nDataLoader의 첫 번째 배치 shape:")
    print(f"batch_x shape: {batch_x.shape}")
    print(f"batch_y shape: {batch_y.shape}")
    print(f"batch_x_mark shape: {batch_x_mark.shape}")
    print(f"batch_y_mark shape: {batch_y_mark.shape}")
    break

In [ ]:
# 데이터 경로 설정
root_path = './ETT-small'
data_path = 'ETTm1.csv'

# 원본 데이터 확인
df = pd.read_csv(os.path.join(root_path, data_path))
print("원본 데이터 shape:", df.shape)
print("\n첫 5행 데이터:")
print(df.head())
print("\n컬럼명:", df.columns.tolist())

# Dataset 인스턴스 생성 (scale=False로 설정)
train_dataset = Dataset_ETT_minute(
    root_path=root_path,
    data_path=data_path,
    flag='train',
    size=[96, 48, 48],  
    features='MS',  
    target='OT',
    scale=False  # StandardScaler 적용하지 않음
)

# 첫 번째 배치 데이터 확인
first_batch = train_dataset[0]
seq_x, seq_y, seq_x_mark, seq_y_mark = first_batch

print("\n첫 번째 배치 데이터:")
print("입력 시퀀스(seq_x) 첫 5행:")
print(seq_x[:5])
print("\n타겟 시퀀스(seq_y) 첫 5행:")
print(seq_y[:5])

# 시간 특성 확인
print("\n시간 특성(seq_x_mark) 첫 5행:")
print(seq_x_mark[:5])
print("\n시간 특성 컬럼:", ['month', 'day', 'weekday', 'hour', 'minute'])

# 데이터 범위 확인
print("\n데이터 범위:")
print("seq_x 범위:", np.min(seq_x), "~", np.max(seq_x))
print("seq_y 범위:", np.min(seq_y), "~", np.max(seq_y))

# 각 변수별 통계량 확인
print("\n입력 시퀀스 기술통계:")
seq_x_df = pd.DataFrame(seq_x)
print(seq_x_df.describe())

# val, test set의 시작시점 확인

In [3]:
# 데이터 경로 설정
root_path = './ETT-small'
data_path = 'ETTm1.csv'

# train, validation, test 데이터셋 생성
datasets = {
    'train': Dataset_ETT_minute(
        root_path=root_path,
        data_path=data_path,
        flag='train',
        size=None,
        features='M',
        scale=False
    ),
    'val': Dataset_ETT_minute(
        root_path=root_path,
        data_path=data_path,
        flag='val',
        size=None,
        features='M',
        scale=False
    ),
    'test': Dataset_ETT_minute(
        root_path=root_path,
        data_path=data_path,
        flag='test',
        size=None,
        features='M',
        scale=False
    )
}

# 각 데이터셋의 시작 시점 확인
for name, dataset in datasets.items():
    first_batch = dataset[0]
    _, _, seq_x_mark, _ = first_batch
    
    # 원본 데이터에서 시간 정보 가져오기
    df_raw = pd.read_csv(os.path.join(root_path, data_path))
    
    # border1 계산
    if name == 'train':
        border1 = 0
    elif name == 'val':
        border1 = 12 * 30 * 24 * 4 - dataset.seq_len
    else:  # test
        border1 = 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4 - dataset.seq_len
    
    # 해당 시점의 실제 날짜 확인
    start_date = pd.to_datetime(df_raw['date'].iloc[border1])
    
    print(f"\n{name.upper()} 데이터셋:")
    print(f"시작 인덱스: {border1}")
    print(f"시작 날짜: {start_date}")
    print("시간 특성 첫 5행 (month, day, weekday, hour, minute):")
    print(seq_x_mark[:5])
    
    # 시작과 끝 시점의 전체 정보
    print(f"\n{name.upper()} 첫 번째 데이터 시점:")
    first_mark = seq_x_mark[0]
    print(f"월: {int(first_mark[0])}, 일: {int(first_mark[1])}, "
          f"요일: {int(first_mark[2])}, 시: {int(first_mark[3])}, "
          f"15분단위: {int(first_mark[4])}")

# 전체 데이터 길이 확인
print("\n전체 데이터 길이:", len(df_raw))
print("각 데이터셋 길이:")
for name, dataset in datasets.items():
    print(f"{name}: {len(dataset)}")

C:\Users\User\AppData\Local\Temp\ipykernel_26276\2425535225.py:62: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  data_stamp = df_stamp.drop(['date'], 1).values
C:\Users\User\AppData\Local\Temp\ipykernel_26276\2425535225.py:62: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  data_stamp = df_stamp.drop(['date'], 1).values



TRAIN 데이터셋:
시작 인덱스: 0
시작 날짜: 2016-07-01 00:00:00
시간 특성 첫 5행 (month, day, weekday, hour, minute):
[[7 1 4 0 0]
 [7 1 4 0 1]
 [7 1 4 0 2]
 [7 1 4 0 3]
 [7 1 4 1 0]]

TRAIN 첫 번째 데이터 시점:
월: 7, 일: 1, 요일: 4, 시: 0, 15분단위: 0

VAL 데이터셋:
시작 인덱스: 34176
시작 날짜: 2017-06-22 00:00:00
시간 특성 첫 5행 (month, day, weekday, hour, minute):
[[ 6 22  3  0  0]
 [ 6 22  3  0  1]
 [ 6 22  3  0  2]
 [ 6 22  3  0  3]
 [ 6 22  3  1  0]]

VAL 첫 번째 데이터 시점:
월: 6, 일: 22, 요일: 3, 시: 0, 15분단위: 0

TEST 데이터셋:
시작 인덱스: 45696
시작 날짜: 2017-10-20 00:00:00
시간 특성 첫 5행 (month, day, weekday, hour, minute):
[[10 20  4  0  0]
 [10 20  4  0  1]
 [10 20  4  0  2]
 [10 20  4  0  3]
 [10 20  4  1  0]]

TEST 첫 번째 데이터 시점:
월: 10, 일: 20, 요일: 4, 시: 0, 15분단위: 0

전체 데이터 길이: 69680
각 데이터셋 길이:
train: 34081
val: 11425
test: 11425


C:\Users\User\AppData\Local\Temp\ipykernel_26276\2425535225.py:62: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  data_stamp = df_stamp.drop(['date'], 1).values


In [5]:
# 데이터 경로 설정
root_path = './ETT-small'
data_path = 'ETTm1.csv'

# 원본 데이터 크기 확인
df = pd.read_csv(os.path.join(root_path, data_path))
print("전체 데이터 크기:", len(df))

# 경계값 계산
seq_len = 24 * 4 * 4    # 384
label_len = 24 * 4      # 96
pred_len = 24 * 4       # 96

border1s = [0, 12 * 30 * 24 * 4 - seq_len, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4 - seq_len]
border2s = [12 * 30 * 24 * 4, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4, 12 * 30 * 24 * 4 + 8 * 30 * 24 * 4]

print("\n각 분할의 경계값:")
splits = ['train', 'validation', 'test']
for i, split in enumerate(splits):
    print(f"\n{split}:")
    print(f"시작 인덱스 (border1): {border1s[i]}")
    print(f"종료 인덱스 (border2): {border2s[i]}")
    print(f"데이터 길이: {border2s[i] - border1s[i]}")

# 이론적인 분할 크기
print("\n이론적인 분할:")
total_minutes = 12 * 30 * 24 * 4  # 1년치
print(f"1년: {total_minutes}")
print(f"4개월: {4 * 30 * 24 * 4}")

# 실제 데이터셋 크기
datasets = {
    'train': Dataset_ETT_minute(
        root_path=root_path,
        data_path=data_path,
        flag='train',
        size=None,
        features='M',
        scale=False
    ),
    'val': Dataset_ETT_minute(
        root_path=root_path,
        data_path=data_path,
        flag='val',
        size=None,
        features='M',
        scale=False
    ),
    'test': Dataset_ETT_minute(
        root_path=root_path,
        data_path=data_path,
        flag='test',
        size=None,
        features='M',
        scale=False
    )
}

print("\n실제 데이터셋 크기:")
for name, dataset in datasets.items():
    print(f"{name}: {len(dataset)}")

전체 데이터 크기: 69680

각 분할의 경계값:

train:
시작 인덱스 (border1): 0
종료 인덱스 (border2): 34560
데이터 길이: 34560

validation:
시작 인덱스 (border1): 34176
종료 인덱스 (border2): 46080
데이터 길이: 11904

test:
시작 인덱스 (border1): 45696
종료 인덱스 (border2): 57600
데이터 길이: 11904

이론적인 분할:
1년: 34560
4개월: 11520


C:\Users\User\AppData\Local\Temp\ipykernel_26276\2425535225.py:62: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  data_stamp = df_stamp.drop(['date'], 1).values
C:\Users\User\AppData\Local\Temp\ipykernel_26276\2425535225.py:62: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  data_stamp = df_stamp.drop(['date'], 1).values



실제 데이터셋 크기:
train: 34081
val: 11425
test: 11425


C:\Users\User\AppData\Local\Temp\ipykernel_26276\2425535225.py:62: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  data_stamp = df_stamp.drop(['date'], 1).values
